---
# https://github.com/grafana/tempo/blob/60780f7ff878d86e0e23179fc65f2c3ed9832e9d/example/docker-compose/shared/prometheus.yaml
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]