flights:
  outputs:
    local:
      type: postgres
      host: localhost
      user: postgres
      pass: p@ssw0rd
      port: 5432
      dbname: postgresdb
      schema: public
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default
      # search_path: [optional, override the default postgres search_path]
      # role: [optional, set the role dbt assumes when executing queries]
      # sslmode: [optional, set the sslmode used to connect to the database]
    airflow:
      type: postgres
      host: postgresdb
      user: postgres
      pass: p@ssw0rd
      port: 5432
      dbname: postgresdb
      schema: public
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default
      # search_path: [optional, override the default postgres search_path]
      # role: [optional, set the role dbt assumes when executing queries]
      # sslmode: [optional, set the sslmode used to connect to the database]
  target: local

