name: datahub
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - libcxx=14.0.6
  - libffi=3.4.2
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=22.2.2
  - python=3.9.13
  - readline=8.1.2
  - sqlite=3.39.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.12
  - pip:
    - acryl-datahub==0.8.45.2
    - acryl-datahub-airflow-plugin==0.9.0.4
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - alembic==1.8.1
    - anyio==3.6.2
    - apache-airflow==2.2.5
    - apache-airflow-providers-common-sql==1.2.0
    - apache-airflow-providers-ftp==3.1.0
    - apache-airflow-providers-http==4.0.0
    - apache-airflow-providers-imap==3.0.0
    - apache-airflow-providers-sqlite==3.2.1
    - apispec==3.3.2
    - argcomplete==2.0.0
    - async-timeout==4.0.2
    - attrs==20.3.0
    - avro==1.10.2
    - avro-gen3==0.7.6
    - babel==2.10.3
    - blinker==1.5
    - cached-property==1.5.2
    - cachelib==0.9.0
    - cattrs==1.10.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==7.1.2
    - click-default-group==1.2.2
    - click-spinner==0.1.10
    - clickclick==20.10.2
    - colorama==0.4.6
    - colorlog==6.7.0
    - commonmark==0.9.1
    - connexion==2.14.1
    - croniter==1.3.7
    - cryptography==38.0.1
    - defusedxml==0.7.1
    - deprecated==1.2.13
    - dill==0.3.6
    - dnspython==2.2.1
    - docker==6.0.0
    - docutils==0.16
    - email-validator==1.3.0
    - entrypoints==0.4
    - expandvars==0.9.0
    - flask==1.1.4
    - flask-appbuilder==3.4.5
    - flask-babel==2.0.0
    - flask-caching==1.11.1
    - flask-jwt-extended==3.25.1
    - flask-login==0.4.1
    - flask-openid==1.3.0
    - flask-session==0.4.0
    - flask-sqlalchemy==2.5.1
    - flask-wtf==0.14.3
    - frozenlist==1.3.1
    - gunicorn==20.1.0
    - h11==0.12.0
    - httpcore==0.15.0
    - httpx==0.23.0
    - humanfriendly==10.0
    - idna==3.4
    - ijson==3.1.4
    - importlib-metadata==5.0.0
    - inflection==0.5.1
    - iso8601==1.1.0
    - itsdangerous==1.1.0
    - jinja2==2.11.3
    - jsonschema==3.2.0
    - lazy-object-proxy==1.8.0
    - lockfile==0.12.2
    - mako==1.2.3
    - markdown==3.4.1
    - markupsafe==2.0.1
    - marshmallow==3.18.0
    - marshmallow-enum==1.5.1
    - marshmallow-oneofschema==3.0.1
    - marshmallow-sqlalchemy==0.26.1
    - mixpanel==4.10.0
    - multidict==6.0.2
    - mypy-extensions==0.4.3
    - packaging==21.3
    - pendulum==2.1.2
    - prison==0.2.1
    - progressbar2==4.0.0
    - psutil==5.9.2
    - pycparser==2.21
    - pydantic==1.10.2
    - pygments==2.13.0
    - pyjwt==1.7.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-daemon==2.3.2
    - python-dateutil==2.8.2
    - python-graphviz==0.20.1
    - python-nvd3==0.15.0
    - python-slugify==4.0.1
    - python-utils==3.3.3
    - python3-openid==3.2.0
    - pytz==2022.4
    - pytz-deprecation-shim==0.1.0.post0
    - pytzdata==2020.1
    - pyyaml==6.0
    - ratelimiter==1.2.0.post0
    - requests==2.28.1
    - requests-toolbelt==0.10.1
    - rfc3986==1.5.0
    - rich==12.6.0
    - setproctitle==1.3.2
    - setuptools==65.4.1
    - six==1.16.0
    - sniffio==1.3.0
    - sqlalchemy==1.3.24
    - sqlalchemy-jsonfield==1.0.0
    - sqlalchemy-utils==0.38.3
    - sqlparse==0.4.3
    - stackprinter==0.2.9
    - swagger-ui-bundle==0.0.9
    - tabulate==0.8.10
    - tenacity==8.1.0
    - termcolor==2.0.1
    - text-unidecode==1.3
    - toml==0.10.2
    - types-deprecated==1.2.9
    - types-termcolor==1.1.6
    - typing-extensions==4.4.0
    - typing-inspect==0.8.0
    - tzdata==2022.4
    - tzlocal==4.2
    - unicodecsv==0.14.1
    - urllib3==1.26.12
    - websocket-client==1.4.1
    - werkzeug==1.0.1
    - wrapt==1.14.1
    - wtforms==2.3.3
    - yarl==1.8.1
    - zipp==3.10.0
