name: datahub
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - libcxx=14.0.6
  - libffi=3.4.2
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=22.2.2
  - python=3.9.13
  - readline=8.1.2
  - sqlite=3.39.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.12
  - pip:
    - acryl-datahub==0.8.45.2
    - acryl-datahub-airflow-plugin==0.9.0.4
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - alembic==1.8.1
    - altair==4.2.0
    - anyio==3.6.2
    - apache-airflow==2.2.5
    - apache-airflow-providers-common-sql==1.2.0
    - apache-airflow-providers-ftp==3.1.0
    - apache-airflow-providers-http==4.0.0
    - apache-airflow-providers-imap==3.0.0
    - apache-airflow-providers-sqlite==3.2.1
    - apispec==3.3.2
    - appnope==0.1.3
    - argcomplete==2.0.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - async-timeout==4.0.2
    - attrs==20.3.0
    - avro==1.10.2
    - avro-gen3==0.7.6
    - babel==2.10.3
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - blinker==1.5
    - cached-property==1.5.2
    - cachelib==0.9.0
    - cattrs==1.10.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==7.1.2
    - click-default-group==1.2.2
    - click-spinner==0.1.10
    - clickclick==20.10.2
    - colorama==0.4.6
    - colorlog==6.7.0
    - commonmark==0.9.1
    - connexion==2.14.1
    - croniter==1.3.7
    - cryptography==38.0.1
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecated==1.2.13
    - dill==0.3.6
    - dnspython==2.2.1
    - docker==6.0.0
    - docutils==0.16
    - email-validator==1.3.0
    - entrypoints==0.4
    - executing==1.2.0
    - expandvars==0.9.0
    - fastjsonschema==2.16.2
    - flask==1.1.4
    - flask-appbuilder==3.4.5
    - flask-babel==2.0.0
    - flask-caching==1.11.1
    - flask-jwt-extended==3.25.1
    - flask-login==0.4.1
    - flask-openid==1.3.0
    - flask-session==0.4.0
    - flask-sqlalchemy==2.5.1
    - flask-wtf==0.14.3
    - frozenlist==1.3.1
    - geoalchemy2==0.11.1
    - great-expectations==0.15.22
    - greenlet==2.0.1
    - gunicorn==20.1.0
    - h11==0.12.0
    - httpcore==0.15.0
    - httpx==0.23.0
    - humanfriendly==10.0
    - idna==3.4
    - ijson==3.1.4
    - importlib-metadata==5.0.0
    - inflection==0.5.1
    - ipykernel==6.17.1
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - iso8601==1.1.0
    - itsdangerous==1.1.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - jsonpatch==1.32
    - jsonpointer==2.3
    - jsonschema==3.2.0
    - jupyter-client==7.4.7
    - jupyter-core==5.0.0
    - jupyter-server==1.23.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - lazy-object-proxy==1.8.0
    - lockfile==0.12.2
    - makefun==1.15.0
    - mako==1.2.3
    - markdown==3.4.1
    - markupsafe==2.0.1
    - marshmallow==3.18.0
    - marshmallow-enum==1.5.1
    - marshmallow-oneofschema==3.0.1
    - marshmallow-sqlalchemy==0.26.1
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - mixpanel==4.10.0
    - multidict==6.0.2
    - mypy-extensions==0.4.3
    - nbclassic==0.4.8
    - nbclient==0.6.3
    - nbconvert==7.2.5
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.23.5
    - packaging==21.3
    - pandas==1.5.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pendulum==2.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.5.4
    - prison==0.2.1
    - progressbar2==4.0.0
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.33
    - psutil==5.9.2
    - psycopg2-binary==2.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pydantic==1.10.2
    - pygments==2.13.0
    - pyjwt==1.7.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-daemon==2.3.2
    - python-dateutil==2.8.2
    - python-graphviz==0.20.1
    - python-nvd3==0.15.0
    - python-slugify==4.0.1
    - python-utils==3.3.3
    - python3-openid==3.2.0
    - pytz==2022.4
    - pytz-deprecation-shim==0.1.0.post0
    - pytzdata==2020.1
    - pyyaml==6.0
    - pyzmq==24.0.1
    - ratelimiter==1.2.0.post0
    - requests==2.28.1
    - requests-toolbelt==0.10.1
    - rfc3986==1.5.0
    - rich==12.6.0
    - ruamel-yaml==0.17.17
    - ruamel-yaml-clib==0.2.7
    - scipy==1.9.3
    - send2trash==1.8.0
    - setproctitle==1.3.2
    - setuptools==65.4.1
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - sqlalchemy==1.3.24
    - sqlalchemy-jsonfield==1.0.0
    - sqlalchemy-utils==0.38.3
    - sqlparse==0.4.3
    - stack-data==0.6.1
    - stackprinter==0.2.9
    - swagger-ui-bundle==0.0.9
    - tabulate==0.8.10
    - tenacity==8.1.0
    - termcolor==2.0.1
    - terminado==0.17.0
    - text-unidecode==1.3
    - tinycss2==1.2.1
    - toml==0.10.2
    - toolz==0.12.0
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.2.1.post0
    - types-deprecated==1.2.9
    - types-termcolor==1.1.6
    - typing-extensions==4.4.0
    - typing-inspect==0.8.0
    - tzdata==2022.4
    - tzlocal==4.2
    - unicodecsv==0.14.1
    - urllib3==1.26.12
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - werkzeug==1.0.1
    - widgetsnbextension==4.0.3
    - wrapt==1.14.1
    - wtforms==2.3.3
    - yarl==1.8.1
    - zipp==3.10.0
