ARG AIRFLOW_VERSION=2.6.0
ARG PYTHON_VERSION=3.9
FROM apache/airflow:${AIRFLOW_VERSION}-python${PYTHON_VERSION}

ARG DAG_SUBDIR
RUN pip install pandas pyarrow

COPY . /opt/airflow/dags/${DAG_SUBDIR}/
