version: '3'

services:
  mysql:
    image: mysql:8
    env_file:
      - mysql.env

  ftp-server:
    image: iowoi/sftp-server:latest
    ports:
        - 22:22
    env_file:
      - sftp.env

  airflow:
    image: docker-whirl-airflow:py-${PYTHON_VERSION}-local
    command: ["singlemachine"]
    ports:
      - '5000:5000'  # HTTP (Airflow Web UI)
    env_file:
      - mysql.env
      - sftp.env
      - .whirl.env
    environment:
      - WHIRL_SETUP_FOLDER
      - AIRFLOW__API__AUTH_BACKEND
    volumes:
      - $DAG_FOLDER:/opt/airflow/dags/$PROJECTNAME
      - ${ENVIRONMENT_FOLDER}/whirl.setup.d:${WHIRL_SETUP_FOLDER}/env.d/
      - ${DAG_FOLDER}/whirl.setup.d:${WHIRL_SETUP_FOLDER}/dag.d/
      - ${MOCK_DATA_FOLDER}:/mock-data
    depends_on:
      - ftp-server
      - mysql
