flights:
  outputs:
    hive:
      type: spark
      method: thrift
      host: sparkthrift
      port: 10000
      user: hive
      password: hive
      schema: default
      connect_retries: 5
      connect_timeout: 60
  target: hive

