name: Publish minimal release archive
on:
  release:
    permissions:
      contents: write  # for actions/upload-release-asset to upload release asset
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run git-archive command to create a release artifact
        run: git archive --format=tar.gz --prefix=whirl/ --output=whirl-release.tgz HEAD

      - name: Test existance
        run: ls -la

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./whirl-release.tgz
          asset_name: Whirl release
          asset_content_type: application/gzip